<a href="https://colab.research.google.com/github/garfield-gray/Calculations/blob/main/Covariance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import numpy as np
from sklearn import datasets
data = datasets.load_iris()
A = data.data

In [77]:
A.shape

(150, 4)

[[ 0.68569351 -0.042434    1.27431544  0.51627069]
 [-0.042434    0.18997942 -0.32965638 -0.12163937]
 [ 1.27431544 -0.32965638  3.11627785  1.2956094 ]
 [ 0.51627069 -0.12163937  1.2956094   0.58100626]]


In [49]:
c.shape

(4, 4)

In [50]:
A.T@A

array([[5223.85, 2673.43, 3483.76, 1128.14],
       [2673.43, 1430.4 , 1674.3 ,  531.89],
       [3483.76, 1674.3 , 2582.71,  869.11],
       [1128.14,  531.89,  869.11,  302.33]])

In [56]:
(A.T@A-(150-2)*(A.T@np.ones([150,150])@A))/150

array([[-757974.061     , -396585.5718    , -487472.05093333,
        -155572.39773333],
       [-396585.5718    , -207500.23786667, -255054.8204    ,
         -81398.56553333],
       [-487472.05093333, -255054.8204    , -313503.70273333,
        -100051.70753333],
       [-155572.39773333,  -81398.56553333, -100051.70753333,
         -31930.47433333]])

In [78]:
((A-(np.ones([150, 150])@A)/150).T@(A-(np.ones([150, 150])@A)/150))/150

array([[ 0.68112222, -0.04215111,  1.26582   ,  0.51282889],
       [-0.04215111,  0.18871289, -0.32745867, -0.12082844],
       [ 1.26582   , -0.32745867,  3.09550267,  1.286972  ],
       [ 0.51282889, -0.12082844,  1.286972  ,  0.57713289]])

In [79]:
np.cov(A.T)

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [80]:
(A.T@A - A.T@np.ones([150, 150])@A/150)/150

array([[ 0.68112222, -0.04215111,  1.26582   ,  0.51282889],
       [-0.04215111,  0.18871289, -0.32745867, -0.12082844],
       [ 1.26582   , -0.32745867,  3.09550267,  1.286972  ],
       [ 0.51282889, -0.12082844,  1.286972  ,  0.57713289]])

In [114]:
# Booooooy!!

mean = np.ones([1, 150])@A/150

A.T@A/150 - mean.T@mean

array([[ 0.68112222, -0.04215111,  1.26582   ,  0.51282889],
       [-0.04215111,  0.18871289, -0.32745867, -0.12082844],
       [ 1.26582   , -0.32745867,  3.09550267,  1.286972  ],
       [ 0.51282889, -0.12082844,  1.286972  ,  0.57713289]])

In [113]:
mean = np.ones([1, 150])@A/150
150*mean.T@mean

array([[5121.68166667, 2679.75266667, 3293.887     , 1051.21566667],
       [2679.75266667, 1402.09306667, 1723.4188    ,  550.01426667],
       [3293.887     , 1723.4188    , 2118.3846    ,  676.0642    ],
       [1051.21566667,  550.01426667,  676.0642    ,  215.76006667]])

In [97]:
A.T@np.ones([150, 150])@A/150

array([[5121.68166667, 2679.75266667, 3293.887     , 1051.21566667],
       [2679.75266667, 1402.09306667, 1723.4188    ,  550.01426667],
       [3293.887     , 1723.4188    , 2118.3846    ,  676.0642    ],
       [1051.21566667,  550.01426667,  676.0642    ,  215.76006667]])

In [95]:
np.ones(150)@A/150

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [87]:
(A.T@np.ones([150, 150])@A/150)[0]/np.linalg.norm((A.T@np.ones([150, 150])@A/150)[0], 2)

array([0.76039706, 0.39785293, 0.48903117, 0.15607009])

In [88]:
(A.T@np.ones([150, 150])@A/150)[1]/np.linalg.norm((A.T@np.ones([150, 150])@A/150)[1], 2)

array([0.76039706, 0.39785293, 0.48903117, 0.15607009])

In [89]:
(A.T@np.ones([150, 150])@A/150)[2]/np.linalg.norm((A.T@np.ones([150, 150])@A/150)[2], 2)

array([0.76039706, 0.39785293, 0.48903117, 0.15607009])

In [90]:
(A.T@np.ones([150, 150])@A/150)

array([[5121.68166667, 2679.75266667, 3293.887     , 1051.21566667],
       [2679.75266667, 1402.09306667, 1723.4188    ,  550.01426667],
       [3293.887     , 1723.4188    , 2118.3846    ,  676.0642    ],
       [1051.21566667,  550.01426667,  676.0642    ,  215.76006667]])