In [3]:
using Distributions 

In [27]:
o = [rand(Uniform(-4,-3), 10) rand(Uniform(0, 0.5), 10)]
o[4]

-3.4951255407981905

In [16]:
rand(1, 2)
Uniform(0,0.6)

Uniform{Float64}(a=0.0, b=0.6)

In [4]:
function obj1(x)
    return (3*x[:,1].^2 + 12*x[:,2].^2 + 10*x[:,1]).^2 + ((24*x[:,1].*x[:,2] + 4*x[:,2]).+3).^2  
end

obj1 (generic function with 1 method)

In [26]:
#Particle Swarm Optimization instant 1
# Define PSO Parameters
N = 2                     # Number of variables
NP = 10                   # Number of particles
MAXIT = 40                # Maximum Number of iterations
Dmp = 1                   # Inertia weight damping ratio
###############################################################################################
a1 = 2.05; a2 = 2.05; phi = a1+a2; w = 2/abs(2-phi-sqrt(phi^2-4*phi)); c1 = w*a1; c2 = w*a2;
x = [rand(Uniform(-4,-3), 10) rand(Uniform(0, 0.5), 10)]; # if we widen the range, it may find the other point!
f = obj1(x); xlb = x; flb = f;
(fgb,i) = findmin(flb); xgb = xlb[i,:];
v = zeros(NP,N); Best = NaN*ones(MAXIT,1);

for t in 1:MAXIT
    v = w*v+c1*rand(NP,N).*(xlb-x)+c2*rand(NP,N).*(repeat(xgb',NP,1)-x); 
    #v = min(max(v,-vl),vl);
    x = x+v; 
    #in = (x<R1 | x>R2) ;
    #v(in) = -v(in); x = min(max(x,R1),R2);
    f = obj1(x);
    i = findall(f.<flb); xlb[i,:] = x[i,:]; flb[i] = f[i];
    (fgb,i) = findmin(flb); xgb = xlb[i,:];
    Best[t] = fgb; w = w*Dmp;
end

xmin = xgb; fmin = fgb
print(xmin)

[-3.331764238095355, 0.039422583596212965]

In [48]:
#Particle Swarm Optimization instant 1
#defining the objective function
K = zeros(6)
for k in 1:6
    K[k] = 500 + 200*(5/3-k-1)^2
end
W = zeros(5)
for w in 1:5
    W[w] = 50*(w+1)
end

function obje2(x)
    PE = 0
    PE += 1/2*K[1]*(sqrt.(((x[:,1].-0).^2 + (x[:,6].-0).^2)).-10).^2
    
    return PE
end

# Define PSO Parameters
N = 2                     # Number of variables
NP = 10                   # Number of particles
MAXIT = 40                # Maximum Number of iterations
Dmp = 1                   # Inertia weight damping ratio


x = [10, 21, 31, 42, 51, -4, -7, -9, -9, -6]
y = repeat(x',NP,1)
obje2(y)

LoadError: MethodError: no method matching +(::Int64, ::Vector{Float64})
For element-wise addition, use broadcasting with dot syntax: scalar .+ array
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Union{Int16, Int32, Int64, Int8}, ::BigInt) at gmp.jl:534
  ...

In [1]:
P = [0 0.1 0 0 0.9 0 0 0 0 0 0 0
    0.05 0 0.05 0 0 0.9 0 0 0 0 0 0
    0 0 1 0 0 0 0 0 0 0 0 0
    0 0 0 1 0 0 0 0 0 0 0 0
    0.05 0 0 0 0 0.9 0 0 0.05 0 0 0
    0 0 0 0 0.05 0 0.05 0 0 0.9 0 0
    0 0 0 0 0 0 1 0 0 0 0 0
    0 0 0 0.9 0 0 0.1 0 0 0 0 0
    0 0 0 0 0 0 0 0 1 0 0 0
    0 0 0 0 0 0.1 0 0 0 0 0.9 0
    0 0 0 0 0 0 0.1 0 0 0 0 0.9
    0 0 0 0 0 0 0 0.9 0 0 0.1 0]

12×12 Matrix{Float64}:
 0.0   0.1  0.0   0.0  0.9   0.0  0.0   0.0  0.0   0.0  0.0  0.0
 0.05  0.0  0.05  0.0  0.0   0.9  0.0   0.0  0.0   0.0  0.0  0.0
 0.0   0.0  1.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0  0.0
 0.0   0.0  0.0   1.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0  0.0
 0.05  0.0  0.0   0.0  0.0   0.9  0.0   0.0  0.05  0.0  0.0  0.0
 0.0   0.0  0.0   0.0  0.05  0.0  0.05  0.0  0.0   0.9  0.0  0.0
 0.0   0.0  0.0   0.0  0.0   0.0  1.0   0.0  0.0   0.0  0.0  0.0
 0.0   0.0  0.0   0.9  0.0   0.0  0.1   0.0  0.0   0.0  0.0  0.0
 0.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0  1.0   0.0  0.0  0.0
 0.0   0.0  0.0   0.0  0.0   0.1  0.0   0.0  0.0   0.0  0.9  0.0
 0.0   0.0  0.0   0.0  0.0   0.0  0.1   0.0  0.0   0.0  0.0  0.9
 0.0   0.0  0.0   0.0  0.0   0.0  0.0   0.9  0.0   0.0  0.1  0.0

In [2]:
P*[1 1 1 1 1 1 1 1 1 1 1 1]'

12×1 Matrix{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [3]:
function MDP(r,g,p,n)   #(r,g,p,n) = (reward,gamma,probability,iteration)
    v = r
    for i in 1:n
        x = g*p*v
        v = x
    end
    return v
end

MDP (generic function with 1 method)

In [4]:
R = [0 0 -50 20 0 0 -50 0 2 0 0 0]'
MDP(R,1,P,50)

12×1 Matrix{Float64}:
   2.4968601867930746
   0.15686018679307434
 -50.0
  20.0
   2.7568601867930744
   2.8133524193926895
 -50.0
  13.0
   2.0
   5.75056601117004
   6.076923076923078
  12.307692307692308

In [8]:
s1=1;s2=2;
print(s1)

1